### ISSUE TITLE
Full-range switch statements fail

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#70]
When a `switch()` statement covers the full range of int values, it seems to be completely skipped instead. For example, the following function throws an error no matter what value is passed in, even though logically this should never happen:

```
#include <limits.h>

int test(int n)
{
    switch (n) {
	case INT_MIN..-1: return -1;
	case 0: return 0;
	case 1..INT_MAX: return 1;
    }
    error("Shouldn't be able to reach this point");
}
```

Changing `INT_MIN` to, say, `(INT_MIN+1)` will make the `switch` statement work, so an obvious workaround is to use `default` in place of any one of the `case` statements.

**Comment by dworkin** [comment]
Interesting bug!

**Comment by dworkin** [comment]
Should be fixed by b56db2381f3ba604f7e4232746fa1682a3c7b6e9.

**Comment by nyankers** [comment]
Aha, was confused at first because it was still happening, forgot it was a fix in the compiler and the object had to be recompiled. It's fixed now, thank you! <3
